
# Generated by Django 5.2.6 on 2025-10-05 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.student'),
        ),
    ]
