# Generated by Django 5.2.6 on 2025-10-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=0),
        ),
    ]
