# Generated by Django 5.2.6 on 2025-10-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='letter',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
