# Generated by Django 5.2.6 on 2025-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_grade_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='lecturer_profiles', to='reports.course'),
        ),
    ]
